const fontsNgin = {
    // --- SANS-SERIF (Modern & Professional) ---
    'Norse': ['Norse', 'sans-serif'],
    'Norsebold': ['Norsebold', 'sans-serif'],
    'Inter': ['Inter', 'sans-serif'],
    'Roboto': ['Roboto', 'sans-serif'],
    'Open Sans': ['Open Sans', 'sans-serif'],
    'Poppins': ['Poppins', 'sans-serif'],
    'Montserrat': ['Montserrat', 'sans-serif'],
    'Outfit': ['Outfit', 'sans-serif'],
    'Plus Jakarta Sans': ['Plus Jakarta Sans', 'sans-serif'],
    'DM Sans': ['DM Sans', 'sans-serif'],
    'IBM Plex Sans': ['IBM Plex Sans', 'sans-serif'],
    'Nunito': ['Nunito', 'sans-serif'],
    'Lato': ['Lato', 'sans-serif'],
    'Geist': ['Geist', 'sans-serif'],
    'Barlow': ['Barlow', 'sans-serif'],
    'Public Sans': ['Public Sans', 'sans-serif'],
    'Work Sans': ['Work Sans', 'sans-serif'],
    'Manrope': ['Manrope', 'sans-serif'],
    'Urbanist': ['Urbanist', 'sans-serif'],
    'Figtree': ['Figtree', 'sans-serif'],
    'Archivo': ['Archivo', 'sans-serif'],
    // --- SERIF (Luxury & Editorial) ---
    'Merriweather': ['Merriweather', 'serif'],
    'Playfair Display': ['Playfair Display', 'serif'],
    'Lora': ['Lora', 'serif'],
    'Source Serif 4': ['Source Serif 4', 'serif'],
    'Libre Baskerville': ['Libre Baskerville', 'serif'],
    'Space Grotesk': ['Space Grotesk', 'sans-serif'], // Grotesk is technically sans-like
    'PT Serif': ['PT Serif', 'serif'],
    'Fraunces': ['Fraunces', 'serif'],
    'Cormorant Garamond': ['Cormorant Garamond', 'serif'],
    'Crimson Pro': ['Crimson Pro', 'serif'],
    'EB Garamond': ['EB Garamond', 'serif'],
    'Newsreader': ['Newsreader', 'serif'],
    'DM Serif Display': ['DM Serif Display', 'serif'],
    'Prata': ['Prata', 'serif'],
    'Bodoni Moda': ['Bodoni Moda', 'serif'],
    'Young Serif': ['Young Serif', 'serif'],
    // --- MONOSPACE (Technical & Code) ---
    'JetBrains Mono': ['JetBrains Mono', 'monospace'],
    'Fira Code': ['Fira Code', 'monospace'],
    'Geist Mono': ['Geist Mono', 'monospace'],
    'IBM Plex Mono': ['IBM Plex Mono', 'monospace'],
    'Roboto Mono': ['Roboto Mono', 'monospace'],
    'Space Mono': ['Space Mono', 'monospace'],
    'Source Code Pro': ['Source Code Pro', 'monospace'],
    'Inconsolata': ['Inconsolata', 'monospace'],
    'Ubuntu Mono': ['Ubuntu Mono', 'monospace'],
    'Red Hat Mono': ['Red Hat Mono', 'monospace'],
    'Nanum Gothic Coding': ['Nanum Gothic Coding', 'monospace'],
    'Cutive Mono': ['Cutive Mono', 'monospace'],
    // --- DISPLAY & EXPERIMENTAL (Brutalist & Playful) ---
    'Gabriela': ['Gabriela', 'serif'],
    'Delius Swash Caps': ['Delius Swash Caps', 'cursive'],
    'Sora': ['Sora', 'sans-serif'],
    'Bricolage Grotesque': ['Bricolage Grotesque', 'sans-serif'],
    'Clash Display': ['Clash Display', 'sans-serif'],
    'Syne': ['Syne', 'sans-serif'],
    'Unbounded': ['Unbounded', 'sans-serif'],
    'Cabinet Grotesk': ['Cabinet Grotesk', 'sans-serif'],
    'Righteous': ['Righteous', 'cursive'],
    'Lexend': ['Lexend', 'sans-serif'],
    'Kanit': ['Kanit', 'sans-serif'],
}



window.fontsNgin = fontsNgin;
