 const presetsNgin = {
    MODERN: {
        scale: 0.85,
        borderRadius: {
            none: '0',
            sm: '0.2rem',
            DEFAULT: '0.3rem',
            md: '0.4rem',
            lg: '0.5rem',
            xl: '0.75rem',
            '2xl': '1rem',
            '3xl': '1.25rem',
            full: '9999px',
            config: 'var(--radius)'
        },
        fontSize: {
            xs: ['0.7rem', { lineHeight: '1rem' }],
            sm: ['0.8rem', { lineHeight: '1.25rem' }],
            base: ['0.9rem', { lineHeight: '1.5rem' }],
            lg: ['1rem', { lineHeight: '1.75rem' }],
            xl: ['1.15rem', { lineHeight: '1.75rem' }],
            '2xl': ['1.4rem', { lineHeight: '2rem' }],
            '3xl': ['1.75rem', { lineHeight: '2.25rem' }],
            '4xl': ['2rem', { lineHeight: '2.5rem' }],
        },
    },
    CREATIVE: {
        scale: 1.15,
        borderRadius: {
            none: '0',
            sm: '0.5rem',
            DEFAULT: '0.75rem',
            md: '1rem',
            lg: '1.25rem',
            xl: '1.5rem',
            '2xl': '2rem',
            '3xl': '2.5rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.8rem', { lineHeight: '1.2rem' }],
            sm: ['0.95rem', { lineHeight: '1.5rem' }],
            base: ['1.05rem', { lineHeight: '1.75rem' }],
            lg: ['1.2rem', { lineHeight: '2rem' }],
            xl: ['1.4rem', { lineHeight: '2rem' }],
            '2xl': ['1.7rem', { lineHeight: '2.25rem' }],
            '3xl': ['2.1rem', { lineHeight: '2.5rem' }],
            '4xl': ['2.6rem', { lineHeight: '3rem' }],
        },
    },
    TECHNICAL: {
        scale: 1.0,
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            DEFAULT: '0.25rem',
            md: '0.25rem',
            lg: '0.375rem',
            xl: '0.5rem',
            '2xl': '0.625rem',
            '3xl': '0.75rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.75rem', { lineHeight: '1.1rem' }],
            sm: ['0.85rem', { lineHeight: '1.3rem' }],
            base: ['0.95rem', { lineHeight: '1.5rem' }],
            lg: ['1.05rem', { lineHeight: '1.75rem' }],
            xl: ['1.2rem', { lineHeight: '1.75rem' }],
            '2xl': ['1.5rem', { lineHeight: '2rem' }],
            '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
            '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        },
        fontFamily: {
            sans: ['ui-monospace', 'SF Mono', 'Monaco', 'Cascadia Code', 'Courier New', 'monospace'],
            mono: ['ui-monospace', 'SF Mono', 'Monaco', 'Cascadia Code', 'Courier New', 'monospace'],
        },
    },
    FINTECH: {
        scale: 0.75,
        borderRadius: {
            none: '0',
            sm: '0.15rem',
            DEFAULT: '0.25rem',
            md: '0.3rem',
            lg: '0.4rem',
            xl: '0.5rem',
            '2xl': '0.75rem',
            '3xl': '1rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.65rem', { lineHeight: '0.9rem' }],
            sm: ['0.75rem', { lineHeight: '1.1rem' }],
            base: ['0.85rem', { lineHeight: '1.35rem' }],
            lg: ['0.95rem', { lineHeight: '1.5rem' }],
            xl: ['1.05rem', { lineHeight: '1.5rem' }],
            '2xl': ['1.25rem', { lineHeight: '1.75rem' }],
            '3xl': ['1.5rem', { lineHeight: '2rem' }],
            '4xl': ['1.875rem', { lineHeight: '2.25rem' }],
        },
    },
    LUXURY: {
        scale: 1.25,
        borderRadius: {
            none: '0',
            sm: '0',
            DEFAULT: '0',
            md: '0.125rem',
            lg: '0.25rem',
            xl: '0.5rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.7rem', { lineHeight: '1rem', letterSpacing: '0.1em', fontWeight: '300' }],
            sm: ['0.85rem', { lineHeight: '1.25rem', letterSpacing: '0.05em' }],
            base: ['1rem', { lineHeight: '1.75rem', letterSpacing: '0.02em' }],
            lg: ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0.02em' }],
            xl: ['1.75rem', { lineHeight: '2rem', letterSpacing: '-0.02em' }],
            '2xl': ['2.5rem', { lineHeight: '1', letterSpacing: '-0.03em' }],
            '3xl': ['3.5rem', { lineHeight: '1', letterSpacing: '-0.04em' }],
            '4xl': ['5rem', { lineHeight: '1', letterSpacing: '-0.05em' }],
        },
    },
    BRUTALIST: {
        scale: 1.1,
        borderRadius: {
            none: '0',
            sm: '0',
            DEFAULT: '0',
            md: '0',
            lg: '0',
            xl: '0',
            '2xl': '0',
            '3xl': '0',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.75rem', { lineHeight: '1rem', fontWeight: '600' }],
            sm: ['0.875rem', { lineHeight: '1.25rem', fontWeight: '600' }],
            base: ['1.1rem', { lineHeight: '1.5rem', fontWeight: '500' }],
            lg: ['1.5rem', { lineHeight: '1.2', fontWeight: '700' }],
            xl: ['2rem', { lineHeight: '1.1', fontWeight: '800' }],
            '2xl': ['3rem', { lineHeight: '1', fontWeight: '900' }],
            '3xl': ['4.5rem', { lineHeight: '0.9', fontWeight: '900' }],
            '4xl': ['6rem', { lineHeight: '0.8', fontWeight: '900' }],
        },
    },
    EDITORIAL: {
        scale: 1.0,
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            DEFAULT: '0.25rem',
            md: '0.375rem',
            lg: '0.5rem',
            xl: '0.75rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.8rem', { lineHeight: '1.4' }],
            sm: ['0.9rem', { lineHeight: '1.5' }],
            base: ['1.125rem', { lineHeight: '1.7' }], // Larger base for reading
            lg: ['1.35rem', { lineHeight: '1.6' }],
            xl: ['1.8rem', { lineHeight: '1.4' }],
            '2xl': ['2.4rem', { lineHeight: '1.2' }],
            '3xl': ['3.2rem', { lineHeight: '1.1' }],
            '4xl': ['4rem', { lineHeight: '1' }],
        },
    },
    PLAYFUL: {
        scale: 1.05,
        borderRadius: {
            none: '0',
            sm: '0.75rem',
            DEFAULT: '1rem',
            md: '1.25rem',
            lg: '1.5rem',
            xl: '2rem',
            '2xl': '2.5rem',
            '3xl': '3rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.85rem', { lineHeight: '1.2' }],
            sm: ['1rem', { lineHeight: '1.3' }],
            base: ['1.15rem', { lineHeight: '1.4' }],
            lg: ['1.4rem', { lineHeight: '1.4', fontWeight: '700' }],
            xl: ['1.8rem', { lineHeight: '1.3', fontWeight: '800' }],
            '2xl': ['2.2rem', { lineHeight: '1.2', fontWeight: '800' }],
            '3xl': ['2.8rem', { lineHeight: '1.1', fontWeight: '900' }],
            '4xl': ['3.5rem', { lineHeight: '1', fontWeight: '900' }],
        },
    },
    // new
    MINIMALIST: {
        scale: 0.95,
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            DEFAULT: '0.25rem',
            md: '0.375rem',
            lg: '0.5rem',
            xl: '0.625rem',
            '2xl': '0.75rem',
            '3xl': '1rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.7rem', { lineHeight: '1.4' }],
            sm: ['0.8rem', { lineHeight: '1.5' }],
            base: ['0.95rem', { lineHeight: '1.6' }],
            lg: ['1.1rem', { lineHeight: '1.6' }],
            xl: ['1.3rem', { lineHeight: '1.5' }],
            '2xl': ['1.6rem', { lineHeight: '1.4' }],
            '3xl': ['2rem', { lineHeight: '1.3' }],
            '4xl': ['2.5rem', { lineHeight: '1.2' }],
        },
    },
    GAMING: {
        scale: 1.2,
        borderRadius: {
            none: '0',
            sm: '0.375rem',
            DEFAULT: '0.5rem',
            md: '0.625rem',
            lg: '0.75rem',
            xl: '1rem',
            '2xl': '1.5rem',
            '3xl': '2rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.75rem', { lineHeight: '1.1', fontWeight: '600' }],
            sm: ['0.9rem', { lineHeight: '1.2', fontWeight: '600' }],
            base: ['1.05rem', { lineHeight: '1.4', fontWeight: '600' }],
            lg: ['1.3rem', { lineHeight: '1.3', fontWeight: '700' }],
            xl: ['1.6rem', { lineHeight: '1.2', fontWeight: '800' }],
            '2xl': ['2.2rem', { lineHeight: '1.1', fontWeight: '800' }],
            '3xl': ['3rem', { lineHeight: '1', fontWeight: '900' }],
            '4xl': ['4rem', { lineHeight: '0.9', fontWeight: '900' }],
        },
    },
    MEDICAL: {
        scale: 0.9,
        borderRadius: {
            none: '0',
            sm: '0.25rem',
            DEFAULT: '0.375rem',
            md: '0.5rem',
            lg: '0.625rem',
            xl: '0.75rem',
            '2xl': '1rem',
            '3xl': '1.25rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.7rem', { lineHeight: '1.3' }],
            sm: ['0.8rem', { lineHeight: '1.4' }],
            base: ['0.95rem', { lineHeight: '1.6' }],
            lg: ['1.1rem', { lineHeight: '1.6' }],
            xl: ['1.25rem', { lineHeight: '1.5' }],
            '2xl': ['1.5rem', { lineHeight: '1.4' }],
            '3xl': ['1.875rem', { lineHeight: '1.3' }],
            '4xl': ['2.25rem', { lineHeight: '1.2' }],
        },
    },
    ECOMMERCE: {
        scale: 1.0,
        borderRadius: {
            none: '0',
            sm: '0.25rem',
            DEFAULT: '0.5rem',
            md: '0.625rem',
            lg: '0.75rem',
            xl: '1rem',
            '2xl': '1.25rem',
            '3xl': '1.5rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.75rem', { lineHeight: '1.2' }],
            sm: ['0.875rem', { lineHeight: '1.4' }],
            base: ['1rem', { lineHeight: '1.5' }],
            lg: ['1.125rem', { lineHeight: '1.5', fontWeight: '600' }],
            xl: ['1.35rem', { lineHeight: '1.4', fontWeight: '700' }],
            '2xl': ['1.75rem', { lineHeight: '1.3', fontWeight: '700' }],
            '3xl': ['2.25rem', { lineHeight: '1.2', fontWeight: '800' }],
            '4xl': ['3rem', { lineHeight: '1.1', fontWeight: '800' }],
        },
    },
    CORPORATE: {
        scale: 0.95,
        borderRadius: {
            none: '0',
            sm: '0.125rem',
            DEFAULT: '0.25rem',
            md: '0.375rem',
            lg: '0.5rem',
            xl: '0.625rem',
            '2xl': '0.75rem',
            '3xl': '1rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.7rem', { lineHeight: '1.3', letterSpacing: '0.01em' }],
            sm: ['0.8rem', { lineHeight: '1.4', letterSpacing: '0.01em' }],
            base: ['0.95rem', { lineHeight: '1.6' }],
            lg: ['1.1rem', { lineHeight: '1.6' }],
            xl: ['1.3rem', { lineHeight: '1.5' }],
            '2xl': ['1.6rem', { lineHeight: '1.4' }],
            '3xl': ['2rem', { lineHeight: '1.3' }],
            '4xl': ['2.5rem', { lineHeight: '1.2' }],
        },
    },
    RETRO: {
        scale: 1.15,
        borderRadius: {
            none: '0',
            sm: '0',
            DEFAULT: '0',
            md: '0.125rem',
            lg: '0.25rem',
            xl: '0.375rem',
            '2xl': '0.5rem',
            '3xl': '0.75rem',
            full: '9999px',
        },
        fontSize: {
            xs: ['0.75rem', { lineHeight: '1.2', fontWeight: '500' }],
            sm: ['0.875rem', { lineHeight: '1.3', fontWeight: '500' }],
            base: ['1rem', { lineHeight: '1.4', fontWeight: '500' }],
            lg: ['1.25rem', { lineHeight: '1.3', fontWeight: '600' }],
            xl: ['1.6rem', { lineHeight: '1.2', fontWeight: '700' }],
            '2xl': ['2.2rem', { lineHeight: '1.1', fontWeight: '800' }],
            '3xl': ['3rem', { lineHeight: '1', fontWeight: '800' }],
            '4xl': ['4rem', { lineHeight: '0.9', fontWeight: '900' }],
        },
    },
}

window.presetsNgin = presetsNgin;